### ISSUE TITLE
[FEATURE] Customization & Reordering

### ISSUE THREAD

**Issue by Vinanonymous** [leviFrosty/witness-work#119]
hello i would love to be able to change the color theme and app icon! Also would love to be able to reorder sections in the home section. The timer isn't as important to me but my list of return visits are so I'd like those to be at the top.

Thanks for the great app! Looking forward to more updates

**Comment by leviFrosty** [comment]
Hi @Vinanonymous 

Thanks for writing in :)

In regards to the App Icon, I don't believe I will make this customizable.

Regarding the color theme, however, I might consider adding customization but it will be a lower-priority change if it does happen. (I will keep you updated)

I believe that reordering the home screen would be a useful feature. I will implement this in the coming future.

For all of the requests, I will keep you updated regardless on the development progress. Thanks for your time. If you enjoy the app. Consider giving a review and sharing it with your friends! ❤️ 

Best,
Levi

**Comment by Vinanonymous** [comment]
Awesome thank you! For the icon I was just thinking a dark mode version so that it matches my other apps haha 😆 but no worries if this isn’t a priority. I can always make a shortcut from my home screen with my own image.On May 18, 2024, at 10:58 AM, Levi Wilkerson ***@***.***> wrote:﻿
Hi @Vinanonymous
Thanks for writing in :)
In regards to the App Icon, I don't believe I will make this customizable.
Regarding the color theme, however, I might consider adding customization but it will be a lower-priority change if it does happen. (I will keep you updated)
I believe that reordering the home screen would be a useful feature. I will implement this in the coming future.
For all of the requests, I will keep you updated regardless on the development progress. Thanks for your time. If you enjoy the app. Consider giving a review and sharing it with your friends! ❤️
Best,
Levi

**Comment by leviFrosty** [comment]
Good news! This feature has been implemented as part of 98aac46cbc450eab683ab3c13c7cd03b181f40dc
It will be added as part of the next release :)

Thanks for your patience.

Levi
