### ISSUE TITLE
[FEATURE] Remove Rounding on Add Time Screen

### ISSUE THREAD

**Issue by danilodferreira2** [leviFrosty/witness-work#156]
**Is your feature request related to a problem? Please describe.**
The stopwatch only marks the time every 5 minutes and rounds the stopwatch time.

**Describe the solution you'd like**
Mark the correct time every minute and round only the seconds. Ex.: 1:53:45 > It will mark 1:53 or 1:54

Overall, I like your app. It's practical and easier to schedule return visits and studies than Field Service.
Tranks Brother!

**Comment by leviFrosty** [comment]
@danilodferreira2 
Hi. Thanks for the ticket. I'm glad you enjoy using WitnessWork. It's a labor of love.

I will remove the rounding.

I'll update you once this is implemented. After which, it will appear in the next release.

Yours,
Levi

**Comment by leviFrosty** [comment]
Hello,

This feature has been implemented with: cc05b9524aecddb5c2de97d3dbd95b869b1d32be

Thank you for your ticket. Expect to see this feature in the next release.

Yours,
Levi
