### ISSUE TITLE
Monthly Routine Not Opening When Clicked

### ISSUE THREAD

**Issue by igmace** [leviFrosty/witness-work#157]
**Describe the bug**

After the update, when I click on the current month my monthly routine does not open up. It shows that I have clicked on the month but nothing happens.

**To Reproduce**

1. Select current month under Monthly Routine section

**Expected behavior**

Before, I could select the current month and it would open the monthly routine where I could plan my service schedule & track my hours.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Draw on images if possible)

![image](https://github.com/user-attachments/assets/d71255fa-ea2c-4846-b5b8-5fedf0671c33)

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 15 Pro Max]
- OS: [e.g. iOS 17.1.2]
- Version [e.g. 1.9.0]

**Additional context**

**Comment by leviFrosty** [comment]
@igmace 
Hello! Thanks for the issue. Perhaps this is more of a UX problem, it shouldn't feel like you can click that button.

Currently you're in 'Publisher' mode. To view the 'Month' or 'Year' tab, you need to change to anything other than Publisher. For example:

Try: Settings > Preferences > Publisher > Custom > Hour Requirement: 0 (Or whatever your personal goal is)

This will allow you to view the month screen tab at the bottom.

I'll update the buttons in the Monthly Routine section to not appear to 'click' when you're a publisher so it's clear that they don't have functionality anymore.

Please let me know if this has resolve your issue.

Yours,
Levi

**Comment by igmace** [comment]
Hi Levi!

Ahh that makes sense! I didn’t even realize it changed to publisher. I just
started using the app a couple of weeks ago so I couldn’t remember any of
my settings.

I appreciate your quick response - especially on the weekend! Thank you for
creating such a great app. It’s the best one I’ve found! The UI is very
clean & the app has everything I need without being confusing!

Iris Mace

**Comment by leviFrosty** [comment]
@igmace 

Thanks for the kind words :) I'm glad it works well for you and I'm glad this resolved your issue.

I hope you continue to enjoy WitnessWork and tell your friends about it, it's a labor of love.

Yours,
Levi
