### ISSUE TITLE
[Kinyarwanda Translation]

### ISSUE THREAD

**Issue by semana-divin** [leviFrosty/witness-work#163]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
I wouldn't not say that this is a problem. But as we start to use the WitnessWork customarily here in Rwanda, some brothers claimed it to be their native language.

**Describe the solution you'd like**
A translation work can be made, and some brothers will be happy to help with the improvement of accurate translation.

**Comment by leviFrosty** [comment]
Hi!

Thanks for your suggestion. I have just added the Kinyarwanda to the app and to Crowdin.

I'll need your help to get Kinyarwanda translated fully and continue to translate as the app grows. Please translate it here: https://crowdin.com/project/jw-time 

Thank you so much, I hope you continue to enjoy WitnessWork! Have a great week.

Yours,
Levi

**Comment by semana-divin** [comment]
Thank you so much, I'll start right away... This will be soo commendable
here in Rwanda
