### ISSUE TITLE
[BUG] Android Unable to Delete Plan

### ISSUE THREAD

**Issue by semana-divin** [leviFrosty/witness-work#165]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Again, i didn't precise it last time but i would like to be able to delete and edit the already planned schedule.

**Comment by leviFrosty** [comment]
@semana-divin 

Did the above resolve your issue?

Yours,
Levi

**Comment by semana-divin** [comment]
@leviFrosty 
It did not work...
Maybe it may be caused by that am using an android,
the sliding function is not working. Can't slide left or right.

Divin

**Comment by leviFrosty** [comment]
@semana-divin 

Interesting. I'll take a look at this to see if I can reproduce. Apologies for the inconvenience.

**Comment by leviFrosty** [comment]
@semana-divin 

I've found the issue. It appears to have been a long-running issue that no one notified me of. Thank you for reporting this.

Fix included in: 1e3803845981aa95d16440ac4289d7dc4d6805fb

Once again, sorry this is happening. I'm working on getting this release pushed to the Play Store as soon as possible.

Please let me know if you have any other questions or concerns. For now I'm going to close this ticket.

Yours,
Levi

**Comment by semana-divin** [comment]
Its a work in progress! So far no other...
