### ISSUE TITLE
Use latitude and longitude 

### ISSUE THREAD

**Issue by wilsonowilson** [leviFrosty/witness-work#168]
**Is your feature request related to a problem? Please describe.**

I work in a territory where houses aren't marked with precise addresses. So I can't add contact addresses in the app.

**Describe the solution you'd like**
It would be incredible if the app could automatically use latitude and longitude as a replacement for addresses. With a mark location button or similar. That way I wouldn't need to tap an address every time.

**Describe alternatives you've considered**

Right now I literally take a picture of the students home so I can recognize it 😅

**Additional context**

Anyways this is an incredible app. I first used it a few months ago and it was too barebones for me. But I signed up again and was blown away by how much it improved and instantly decided to donate.

**Comment by leviFrosty** [comment]
Hi @wilsonowilson 

Good news, this feature has already been implemented with b1482f1 and is being released as part of the upcoming version.

Thank you for enjoying WitnessWork.

I'll mark this as closed but you can ask me anything if you wish.

Yours,
Levi
