### ISSUE TITLE
[FEATURE] Language Selector

### ISSUE THREAD

**Issue by semana-divin** [leviFrosty/witness-work#170]
**Describe the bug**
There is no button to switch or toggle the languages.

**Expected behavior**
Expected an ease of switch between different translations. If i could get video tutorial, it would be very helpful.

**Smartphone (please complete the following information):**

- Device: [Samsung Galaxy A72]
- OS: [Android 14]
- Version [OneUI 6]

**Comment by semana-divin** [comment]
![Screenshot_20240902_184407_WitnessWork](https://github.com/user-attachments/assets/996ba957-bda6-491e-82d4-81fdd5245ea6)
Also, the planned hours is not getting added up correctly.(If you count the total planned hours, and the statement made below)

**Comment by leviFrosty** [comment]
Hi,

Thanks for writing in for a feature request. I've received more requests to add a language selector, so I will be implementing this soon - I'll update you when this is complete.

As for the scheduling, I'm not sure what is going on with yours. I just trie dot recreate your schedule and time entries - but it worked fine for me. What app version are you on? Can you please go to the app store and update to the latest version?

Please see image example:
![IMG_5EB066187994-1](https://github.com/user-attachments/assets/0a6e8797-2ef4-4dd6-bd9e-b78d3cb74a8c)

Thanks!
Levi

**Comment by leviFrosty** [comment]
@semana-divin 

Great news! This feature has just been implemented with 446bb85a9459080ee1e798d8b863c1d3937d9435

Thank you for your patience. And I hope you enjoy this feature.

As for your scheduling issue, I will assume this has worked itself out. If you still have an issue, please reply to this thread and I will be happy to assist further!

Expect the language selector to be a part of the upcoming release.

Yours,
Levi
