### ISSUE TITLE
[BUG] Date Selector Maximum Date Inaccurate

### ISSUE THREAD

**Issue by Sunshinek13** [leviFrosty/witness-work#172]
Under plan schedule please allow us to select a day “one time” for future dates.
I would like to plan for a future day (example Sep 23, 2024 for 2 hours, only for the month of Sep)
However it won’t allow me to do so unless I click reoccurring, which I do not want. 

So please allow to plan for one time day for future dates.
Thank you

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leviFrosty** [comment]
@Sunshinek13 

Hi, thanks for writing in. I understand that you wish to create one-time plans, but for some reason the app is not allowing you to. Currently this is supported within WitnessWork, so I'm unsure what's going on here.

Can you send me a video reproducing your problems so I can better visually understand what's happening?

Yours,
Levi

**Comment by Sunshinek13** [comment]
Hello,I do not know how to create a video but I am attaching a screenshot of my problem.You will see when I try to plan for “one time” schedule, I am not allowed to select a future date. Sincerely,Jovani Maruyama, RN, BSN“When I am afraid, I put my trust in you.”​—PS. 56:3.On Sep 3, 2024, at 9:56 PM, Levi Wilkerson ***@***.***> wrote:﻿
@Sunshinek13
Hi, thanks for writing in. I understand that you wish to create one-time plans, but for some reason the app is not allowing you to. Currently this is supported within WitnessWork, so I'm unsure what's going on here.
Can you send me a video reproducing your problems so I can better visually understand what's happening?
Yours,
Levi

**Comment by leviFrosty** [comment]
@Sunshinek13 

I see the issue! Thanks for catching this. Currently the UI displays a maximum date of today even if you select a date in the future.

Although confusing, you can still select a date in the future and create a one-time plan. It will appear to be "September 4th" (or the current day), but in reality the data is pointing to the date you tapped from the Calendar.

Please try to create the one-time plan anyways, ignoring the schedule screen, and see if this works around your issue.

I will be pushing a fix to resolve this UI inaccuracy. Apologies for the confusion. This fix will be pushed to the next app version which will release very soon.

Yours,
Levi

**Comment by leviFrosty** [comment]
Fixed with 003fc78f5ef4ee6e2f57753ee182be5d92674c37

**Comment by Sunshinek13** [comment]
Thanks so much!Sincerely,Jovani Maruyama, RN, BSN“When I am afraid, I put my trust in you.”​—PS. 56:3.On Sep 3, 2024, at 11:27 PM, Levi Wilkerson ***@***.***> wrote:﻿
@Sunshinek13
I see the issue! Thanks for catching this. Currently the UI displays a maximum date of today even if you select a date in the future.
Although confusing, you can still select a date in the future and create a one-time plan. It will appear to be "September 4th" (or the current day), but in reality the data is pointing to the date you tapped from the Calendar.
Please try to create the one-time plan anyways, ignoring the schedule screen, and see if this works around your issue.
I will be pushing a fix to resolve this UI inaccuracy. Apologies for the confusion. This fix will be pushed to the next app version which will release very soon.
Yours,
Levi
