### ISSUE TITLE
[ADD] add to The list of forms of service bethel along with service and LDC

### ISSUE THREAD

**Issue by Fbali12** [leviFrosty/witness-work#173]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (Draw on images if possible)

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 15 Pro Max]
- OS: [e.g. iOS 17.1.2]
- Version [e.g. 1.9.0]

**Additional context**

**Comment by leviFrosty** [comment]
Hello, @Fbali12 

Thanks for writing in a ticket. You're requesting to have another prefilled type called "Bethel" - but I do not believe that this is something I will implement.

![IMG_8375](https://github.com/user-attachments/assets/f68140b6-705f-4ae6-a21b-aa22e281b85a)

You can accomplish this on your own by selecting Type > "Other" and then creating your own custom label "Bethel" -- and whether or not your personal service is Credits or not.

![IMG_8376](https://github.com/user-attachments/assets/cff1d6e8-f781-41c1-be03-2cfbc7fc6298)

I hope this helps. Please let me know if you are thinking of something else or if this has resolved your issue.

Yours,
Levi

**Comment by leviFrosty** [comment]
Does the above resolve your issue?

**Comment by Fbali12** [comment]
Yes!! Thanks Inviato da iPhoneIl giorno 6 set 2024, alle ore 05:37, Levi Wilkerson ***@***.***> ha scritto:﻿
Does the above resolve your issue?
