### ISSUE TITLE
[FEATURE] - Transfer Contact

### ISSUE THREAD

**Issue by SimonBuzz** [leviFrosty/witness-work#179]
the ability to send/transfer a contact to another person so they can take over the contact

**Comment by leviFrosty** [comment]
Hi @SimonBuzz 

Thanks for the feature request. This is already on the backlog #93 -- I will be closing this request for now. Please subscribe to #93 to see new information as the feature is being developed.

Thank you for enjoying WitnessWork!

Yours,
Levi

**Comment by SimonBuzz** [comment]
Awesome! Thanks Levi for your hard work bro 😊👍🏻

Do you know when #93 might be instigated?


Kind regards
Simonbuzz

**Comment by leviFrosty** [comment]
@SimonBuzz  I do not know when I'll be able to get to #93 ... I'm currently very busy with life at the moment and pioneering. I'll let you know when I am working on it :)

**Comment by SimonBuzz** [comment]
All good my bro 😊 Definitely make sure of the more important things 👍🏻 @Phil 1:10 😊Enjoy your pioneering 😃WBLSimonOn 10 Sep 2024, at 1:57 AM, Levi Wilkerson ***@***.***> wrote:﻿
@SimonBuzz  I do not know when I'll be able to get to #93 ... I'm currently very busy with life at the moment and pioneering. I'll let you know when I am working on it :)
