### ISSUE TITLE
[FEATURE] Goals by month with no scheduling

### ISSUE THREAD

**Issue by guispdias** [leviFrosty/witness-work#184]
Some may want just a way to know if they are on time on month, on time on service year, how many hours they need in average by day to be on time. With the monthly goal, 50 hours for pioneers, for example, the app could divide by the amount of days in a month. Or even if someone set a monthly goal of 55 hours or 60 as a security margin, the app could calculate too. But the year goal will stay 600.

![image](https://github.com/user-attachments/assets/6d88fa81-d496-4e96-836d-ceff767dac0d)
![IMG_99E18B0459F1-1](https://github.com/user-attachments/assets/c440d9eb-0100-4462-a394-400fbd0c6249)

**Comment by leviFrosty** [comment]
Hi again.

Just so I can make sure I'm understanding, you're wanting a feature that allows you to set a per-month 'Goal', separate from your schedule?

For example:


Before - 
Regular Pioneer
- Annual goal 600
- All months goal 50

After -
Regular Pioneer
- This month override 80 hours
- Annual Goal 600
- All months goal 50

I think it's possible but I'm not sure it's a good user experience over creating a schedule. The intent of the scheduling feature is to do this 'overriding' or 'over scheduling' of a month's goal.

I would suggest you try to schedule out your month, creating and updating your schedule so it goes over the goal.

Let me know if I'm not understanding you correctly.

Yours,
Levi

**Comment by leviFrosty** [comment]
Hi,

Did my previous message resolve your issue?
