### ISSUE TITLE
[FEATURE] annual service hours

### ISSUE THREAD

**Issue by complymo13** [leviFrosty/witness-work#193]
**Is your feature request related to a problem? Please describe.**
I hope the annual service hours will continue from September to August and change to a new service year (from September to August)
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leviFrosty** [comment]
Yes, the annual service hours are matching based on the service year.

If you have a specific question for me, please reply here -- otherwise I will close this ticket.

I hope you continue to enjoy WitnessWork :)

Yours,
Levi
