### ISSUE TITLE
[BUG] iPad Responsiveness Issue

### ISSUE THREAD

**Issue by DouglasReis86** [leviFrosty/witness-work#194]
**Describe the bug**
Problema com responsividade no iPad na vertical
![IMG_0090](https://github.com/user-attachments/assets/a1529aa4-7226-477d-b5a7-8cdb22d9aa87)

na horizontal fica correto.
![IMG_0091](https://github.com/user-attachments/assets/7253de0d-230e-472c-8222-d93a5303fbae)

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (Draw on images if possible)

**Smartphone (please complete the following information):**

- Device: iPad Pro 11”
- OS: iOS 18
- Version: 1.34.0

**Additional context**

**Comment by DouglasReis86** [comment]
Parabéns pelo excelente app. Já indiquei para várias pessoas e fiz minha doação. Espero que mais pessoas usem e doem. 😉

**Comment by leviFrosty** [comment]
@DouglasReis86 

Hi Douglass. Thanks for writing in a bug report.

I am able to replicate this issue and will get it resolved shortly! Thank you for your patience and I'm glad you enjoy WitnessWork.

Yours,
Levi

**Comment by leviFrosty** [comment]
Hi! Thanks for your patience.

This issue has been resolved with 37c45c7b26a6b365dc97e221cac0e65f94d3a45a and will be available in the upcoming update!

Yours,
Levi
