### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Rlima1157** [leviFrosty/witness-work#198]
**Is your feature request related to a problem? Please describe.**
A contact

**Describe the solution you'd like**
A Email  for contact or help

**Describe alternatives you've considered**

**Additional context**

**Comment by leviFrosty** [comment]
@Rlima1157 

Hi, thanks for writing in.

You can add an email to a contact like so:

![image](https://github.com/user-attachments/assets/e7bf3758-fb97-4675-80f1-d4c157306119)

If you have further questions on how to add email, please reply back.

Yours,
Levi
