### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by nommasia** [leviFrosty/witness-work#207]
**Is your feature request related to a problem? Please describe.**
我们常用的日历都是从星期一开始，可以在Schedule设置一个选项从星期一开始或者从星期日开始吗？非常感谢你们爱心的辛劳。愿爸爸祝福你们的努力。
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leviFrosty** [comment]
Hi!

Thank you for your ticket. Yes! This is a feature that I'm working on and will be releasing an update to support this.

Since this is a duplicate of #119 I will be closing this.

Yours,
Levi
